client_id = "a4ee12720079c331fb96a4416c4f9a8e"
name = "auqli-nexus-app"
handle = "auqli-nexus-app"
application_url = "https://auqli-nexus-be.onrender.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
scopes = "read_products, write_products"


[auth]
redirect_urls = [
  "https://auqli-nexus-be.onrender.com/auth/callback",
  "https://auqli-nexus-be.onrender.com/auth/shopify/callback",
  "https://auqli-nexus-be.onrender.com/api/auth/callback"
]

[pos]
embedded = false
