# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "a4ee12720079c331fb96a4416c4f9a8e"
name = "auqli-nexus-app"
handle = "auqli-nexus-app"
application_url = "https://bookmark-mon-kingdom-travesti.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://bookmark-mon-kingdom-travesti.trycloudflare.com/auth/callback",
  "https://bookmark-mon-kingdom-travesti.trycloudflare.com/auth/shopify/callback",
  "https://bookmark-mon-kingdom-travesti.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
